// <auto-generated />
using J7z_E_Commerce.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace J7zECommerce.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221216005701_Categories")]
    partial class Categories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("J7z_E_Commerce.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Books",
                            Url = "books"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Movies",
                            Url = "movies"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Video Games",
                            Url = "video-games"
                        });
                });

            modelBuilder.Entity("J7z_E_Commerce.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "written by Terry Brooks and published on April 21, 1999",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/c/ca/Phantommenacenovel_obiwan.jpg",
                            Price = 9.99m,
                            Title = "Star Wars Episode I: The Phantom Menace"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "The biggest addition to the story is the fact that the Lars family are introduced and have their own subplot leading up to when they appear in the movie.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/5/5d/Attackoftheclones_novel.jpg",
                            Price = 8.99m,
                            Title = "Star Wars: Episode II – Attack of the Clones"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "The lightsaber fight between Anakin, Obi-Wan and Count Dooku is portrayed in far greater detail than in the film.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/8/88/RevengeOfTheSithNovel.jpg",
                            Price = 7.99m,
                            Title = "Star Wars: Revenge of the Sith"
                        });
                });

            modelBuilder.Entity("J7z_E_Commerce.Shared.Product", b =>
                {
                    b.HasOne("J7z_E_Commerce.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
